### PR TITLE
Readme

### LINKED ISSUE #12: update readme.md
-add link to project
-add authors

### PR DESCRIPTION
**Pull request by VytautasKaz**
- added package-lock file
- updated readme

### CODE REVIEW

**Review by justasga — DISMISSED** [review]

**Review by skrendam — DISMISSED** [review]
perfect!

**Review by Justas383 — APPROVED** [review]
Looks good, lets move on!

**Review by Justas383 — APPROVED** [review]
Good thinking, now its a bit clearer!

**Review by Justas383 — DISMISSED** [review]

**Review by justasga — DISMISSED** [review]

**Review by Justas383 — APPROVED** [review]
Everything seems clear

**Review by skrendam — APPROVED** [review]

**Review by skrendam — APPROVED** [review]

**Review by justasga — APPROVED** [review]

**Pull request merged**
